### ISSUE TITLE
# url 스택이 쌓이는 문제

### ISSUE THREAD

**Issue by castberry10** [development-sniff/logbook#3]
![image](https://github.com/development-sniff/logbook/assets/25453543/eb3f580d-25c8-4206-9f54-79b1634abbe4)

여기서 castberry(닉네임) 누르면 url이 쌓이고, 잘못된 GET 요청을 하기때문에 아무런 화면이 나오지 않습니다. 

![image](https://github.com/development-sniff/logbook/assets/25453543/1ce8e3a0-bb88-4c12-83c3-98c078f05332)

**Comment by heeboy007** [comment]
SubInfo 컴포넌트에서 보면 이렇게 Link 코드가 짜여있습니다.
<Link to ={`${username}`}>{username}</Link>
username = "test"라고 하면
그러면 to가 그냥 슬래시 없이 "test" 가 되고, 그럼 relative(상대적) 경로로 인식되서 현재 url에서 test로 내려가게 됩니다.
즉, 이런 형식으로 동작하는 게 원래 맞습니다.

저희가 원하는 건 절대적인 경로이기 때문에 이걸 이렇게 고쳐야 합니다.
<Link to ={`/postlist/${username}`}>{username}</Link>
그러면 to = "/postlist/test" 가 되고 현재 최상단 url에서 /postlist/test를 찾으라는 의미가 됩니다. 
기존처럼 하지 않고 굳이 앞에 /postlist를 붙인 이유는, 어떤 사용자가 Route에 해당하는 id를 가졌을 경우 (login, register등) 예상하기 어려운 형태로 앱이 동작할 수 있어서 그렇습니다. 바로 root url 아래에 변동 가능한 /:username route를 짜는게 보안상, 그리고 실제 메커니즘 상 별로 좋지 않다고 생각합니다.

**Comment by heeboy007** [comment]
고치기 위해서 4개의 소스파일에 /postview 를 더해 주었습니다. 기존과 동일하게 작동하는 것을 체크하였습니다.

WriteActionButton.js의 navigate,
App.js의 Route,
SubInfo.js의 Link,
PostList.js의 PostItemBlock에 있는 Link
