### ISSUE TITLE
footer의 위치가 일정하지 않음

### ISSUE THREAD

**Issue by heeboy007** [development-sniff/logbook#7]
![image](https://github.com/development-sniff/logbook/assets/41155496/9a31290f-322f-4fd9-9a7c-68c2f9a43d56)

지금처럼 아래에 있는 footer의 위치가 일정하지 않습니다. 
css로 calc 함수를 이용해서 위쪽에 가변적인 margin-top을 주는게 제일 구현하긴 어려운데 차후가 편해질 것 같고,
쉬운 건 위에 있는 postlist의 최소 min-height = calc(100vh - (helmet 높이) - (footer 높이)) 로 설정하는건 어떨지 싶습니다.

**Comment by castberry10** [comment]
좋아요
